steps:
- name: 'gcr.io/cloud-builders/go:debian'
  args: ['install', '.']
  env: ['PROJECT_ROOT=github.com/tryggth/tm']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tm:$REVISION_ID', '-t', 'gcr.io/$PROJECT_ID/tm:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tm:$REVISION_ID']
images: ['gcr.io/$PROJECT_ID/tm']
